### ISSUE TITLE
Perpetual update available

### ISSUE THREAD

**Issue by Insomniacxx** [legitcomputerwhisperer/legitcomputerwhisperer.github.io#1]
Not sure if this is the place to mention this, but after updating noncedit, the package stays available in the changes tab as an update =)

**Comment by legitcomputerwhisperer** [comment]
When this happens it's usually due to an issue with cached packages that aren't clearing. Have you tried wiping Cydia's cache with iCleaner Pro and then running "apt-get update" in mterminal afterwards? 

If iCleaner Pro cache cleaning doesn't solve your problem you can also safely manually delete the following cache files: /var/mobile/Library/Caches/com.saurik.Cydia/archives <-delete everything in archives & the partial directory EXCEPT don't delete the "partial" folder itself.

Hope this helps!
